name: CI
on:
  push:
    branches:
      - develop
  pull_request:

jobs:

  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Typecheck SDK and React Native example before building
        run: yarn typecheck

      - name: Pack both release artifacts
        run: yarn packAll
